name: Autofill PR description

on:
  pull_request:
    branches:
      - dev
      - main
      
jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: chalermporn17/openai-pr-description@dev
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}